# -*- coding: utf-8 -*-
"""CodeCarbon-example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBLk-Fne8YCzuwVLiyLU8w0wNsrfh3xq

# Introduction

This tutorial introduces [CodeCarbon](https://codecarbon.io). It shows different ways to use it, and documents some features and behaviours that we discovered while using it. The tutorial is provided as a Google Colab notebook and is designed to be used with GPUs to get the most out of it. You can still use a CPU runtime, but the visualization section will not be useful.

CodeCarbon is a Python library designed to track energy consumption and estimate the related emissions of machine learning tasks, providing various ways to obtain and store the data for visualization and analysis.

The notebook is designed to be run from top to bottom. Be careful about running cells out of order, as you might observe unplanned behaviours.

# CodeCarbon Overview <a name="sec-cc-overview"></a>

As stated, CodeCarbon is a library that provides the tools to track the energy consumption and related emissions of machine learning tasks, especially long-running ones. CodeCarbon can measure the energy consumption of CPUs and GPUs, with fallbacks to heuristics when the libraries that it needs are not available. CodeCarbon also has techniques to estimate the energy consumption of memory. This section provides additional information that is not well documented by the official [CodeCarbon documentation](https://mlco2.github.io/codecarbon/index.html).

## How does CodeCarbon measure energy and power?

Let's explore how CodeCarbon measures the energy and power consumption of different components: the CPU, the RAM, and the GPU. For the CPU and RAM, we mostly summarize and link to the documentation, as it is already quite good. For GPUs, we elaborate on the methodology.

### CPU

The relevant CodeCarbon documentation may be found [here](https://mlco2.github.io/codecarbon/methodology.html).

Measuring the energy consumption of the CPU can be tricky, and varies depending on the operating system  and hardware. Generally speaking, CodeCarbon looks for Intel Power Gadget on Windows/MacOS running on an Intel processor, Powermetrics on MacOS running an ARM chip, and Intel RAPL on Linux (usually supports both Intel and AMD processors).

If none of the tools are available on the system, CodeCarbon has a few fallbacks to proxy the power and energy consumption of the CPU. Notably, it relies on thermal design power (TDP)-- the maximum amount of heat in watts that a CPU generates under typical load. CodeCarbon has a database of various CPU TDPs, which it uses along with PSUtil to compute energy consumption based on CPU usage and the TDP metric. When the TDP is unknown, it uses a constant assumption on the Wattage of the CPU (which can be configured if you know the TDP of your CPU but it is not in their database).

Let's add a bit on Intel RAPL on Linux. The RAPL acronym means Running Average Power Limit. RAPL interfaces provide a way to measure and control power consumption of supported CPUs. Typically, Intel RAPL is visible through the system files found at `/sys/class/powercap/intel-rapl/subsystem`. These files might not be available on a machine. We will not go into the details of Linux kernel modules, how to install and load them, as this is beyond the scope of this tutorial, but know that the relevant module is provided by the package `linux-modules-extra`. You should be able to get more information on the package using `apt info linux-modules-extra-$(uname -r)`.

The CodeCarbon documentation points towards a few references and indirectly references a few more. Here are interesting ones you may want to explore further:

* [RAPL in Action: Experiences in Using RAPL for Power Measurements](https://dl.acm.org/doi/10.1145/3177754)
If you do not have access to the ACM's library, the authors have an accessible PDF of the paper on the university's website [here](https://helda.helsinki.fi/items/27eff093-1585-4568-8784-ab0ff1260b7e)
* [Reading RAPL energy measurements from Linux](https://web.eece.maine.edu/~vweaver/projects/rapl/)
* [Explanation on RAPL / Running Average Power Limit domains: what we (think we) know so far](https://hubblo-org.github.io/scaphandre-documentation/explanations/rapl-domains.html)
* [Intel 64 and IA-32 Architectures Software Developer's Manual Section 14.9](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-system-programming-manual-325384.pdf)
* [Github issue of the Scaphandre project discussing the interpretation of Intel RAPL results](https://github.com/hubblo-org/scaphandre/issues/116#issuecomment-854453231)

### RAM

The relevant CodeCarbon documentation may be found [here](https://mlco2.github.io/codecarbon/methodology.html).

Essentially, CodeCarbon versions prior to v3.0.0 used a constant wattage of 3 Watts per 8GB of RAM as an estimation of the power and energy consumption of RAM. In v3.0.0, they introduced a new heuristic based on the number of RAM slots to account for the fact that the power consumption does not scale linearly with the amount of RAM available. You can read the official documentation for a more detailed explanation on the methodology.

### GPU

The relevant CodeCarbon documentation may be found [here](https://mlco2.github.io/codecarbon/methodology.html). However, they mostly say that they use NVML and leave it at that.

NVML stands for NVidia Management Library. It backs the `nvidia-smi` tool commonly used to query information about the GPU on a system, and can be used to design 3rd party applications. Here are relevant link to it:

* [Official website](https://developer.nvidia.com/management-library-nvml)
* [Online Documentation](https://docs.nvidia.com/deploy/nvml-api/)
* [Reference Manual](https://docs.nvidia.com/deploy/pdf/NVML_API_Reference_Guide.pdf)

The measurements performed by CodeCarbon for GPUs are done using the method `nvmlDeviceGetTotalEnergyConsumption` provided by the library. This method returns the energy consumption of the GPU in millijoules since the driver was last reloaded.

CodeCarbon calculates the difference between two calls to `nvmlDeviceGetTotalEnergyConsumption` to compute the **energy consumption** since the last measurement. Then, the **time difference** between the two measurements and the energy consumption during that period are used to compute the **average power consumption**.

## How does CodeCarbon output data?

<a name="01"></a>

**Output handlers** are objects that CodeCarbon uses to output data during and at the end of experiments. The library already provides quite a few useful ones, which are documented in the [Output section](https://mlco2.github.io/codecarbon/output.html) of the official documentation. In the documentation, they have a little note about the possibility for developers to develop their own output handlers. This can be done by implementing CodeCarbon's `BaseOutput` class. You can find a copy of this class below, taken from [this file](https://github.com/mlco2/codecarbon/blob/be705558f1d7a7243939fc53d3d094acf68d24a0/codecarbon/output_methods/base_output.py).

```python
from typing import List

from codecarbon.output_methods.emissions_data import EmissionsData, TaskEmissionsData


class BaseOutput:
    '''
    An abstract class defining possible contracts for an output strategy, a strategy implementation can save emissions
    data to a file, posting to Json Box, saving to a database, sending a Slack message etc.
    Each method is responsible for a different part of the EmissionsData lifecycle:
        - `out` is used by termination calls such as emissions_tracker.flush and emissions_tracker.stop
        - `live_out` is used by live measurement events, e.g. the iterative update of prometheus metrics
        - `task_out` is used by terminate calls such as emissions_tracker.flush and emissions_tracker.stop, but uses
          emissions segregated by task
    '''

    def out(self, total: EmissionsData, delta: EmissionsData):
        pass

    def live_out(self, total: EmissionsData, delta: EmissionsData):
        pass

    def task_out(self, data: List[TaskEmissionsData], experiment_name: str):
        pass
```

When implementing an output handler, you don't need to implement all three methods. If your use case only requires one of these, then that is all you need to implement.

Let's go over each method.

---
```python
def out(self, total: EmissionData, delta: EmissionData)
```

> As the code snippet says, this method is invoked when the `flush` and `stop` methods of a tracker are called.
> > `total (EmissionData)`: This argument typically contains: energy consumption and emission estimations since tracking began; power measurements since the last measurement; and static information about the experiment such as the operating system, the number of CPUs, GPUs, RAM, etc.
> ---
> > `delta (EmissionData)`: This argument contains the energy consumption, emissions estimations and power consumption between the last two measurements, along with the same static information as in `total`.
---
```python
def live_out(self, total: EmissionsData, delta: EmissionData)
```

> As the code snippet says, this method is used during an experiment to output live measurements. The tracker configuration `api_call_interval` defines after how many measurements this method should be called. The input arguments are the same as for the `out` method.
---
```python
def task_out(self, data: List[TaskEmissionData], experiment_name: str)
```

> This method is used when tracking is divided into different parts called "tasks". Notice that there  are no _total_ or _delta_ distinctions for this method. This is because task measurements are done a little bit differently. An energy measurements is done when the task is started and when it is stopped. The delta is computed between these two measurements, and is used to make a `TaskEmissionData` object for this task.
> > `data (List[TaskEmisisonData])`: This contains the data for each task started during the experiment. The class `TaskEmissionData` is the same as `EmissionData` with the name of the task added. Due to the way measurements are done for tasks, this argument essentially contains a list of _delta_ measurements.
> ---
> > `experiment_name (str)`: This is a configurable parameter of trackers. It allows distinguishing between outputs from `out`/`live_out` and outputs for tasks if needed by the output handler.
---

## How does CodeCarbon track energy, power and emissions?

**Trackers** are the objects provided by CodeCarbon to track energy, power, and emissions. The [Quickstart Guide](https://mlco2.github.io/codecarbon/usage.html) depicts the various ways these can be used. The [Configuration](https://mlco2.github.io/codecarbon/usage.html#configuration) section explains the various ways a tracker can be configured. The [Parameters](https://mlco2.github.io/codecarbon/parameters.html) section explains what each configuration parameter does. Later examples of this tutorial use the `OfflineEmissionTracker` class, but the official documentation contains enough information to understand how to use the other trackers.

Below is a table of some configurable parameters for which we added details.

| Parameter | Description |
| :--- | :--- |
| measure_power_secs | While at first glance this may seem like an integer parameter, it also works with floating points. This allows for sub-second measurements. However, it is <br> important to keep in mind that more frequent measurements can have an impact on the experiment as it requires more resources. Also, very small measurement <br> intervals might not be meaningful. As explained before, power measurements are extrapolated from time and energy measurements. When the energy is queried <br> from NVML for GPUs, the library does not query the GPU. The CUDA drivers keep internal measurements that are updated at constant frequency. This means that a <br> very low interval measurement might measure the same energy twice, so there are no added benefits. On the T4 GPUs, which were used to design this tutorial, a <br> quick test seems to propose that the internal energy counters are updated every 100ms. |
| gpu_ids | On systems with multiple GPUs, this can useful to only track specific GPUs. It can be used to track GPUs individually, but `allow_multiple_runs=True` might <br> be required, depending on your configuration. |
| api_call_interval | This is not only for API calls. It defines after how many measurements the `live_out` method of output handlers is called with new data. Also, we strongly <br> recommend setting this to -1 if the tracker is used to track tasks. Task data is measured as the delta between the start and the end of the task. However, if the <br> measurement done at the end of the task is the one corresponding to when the output handlers are called, the delta of the task will be broken, resulting in energy <br> and emission measurements of zero for this task. This is because the internal method `_compute_emissions_delta` is called to prepare the _delta_ <br> measurement for the output handler, and then immediately called to compute the data for the task. Unfortunately, this method updates the value of <br> `_previous_emissions` of the tracker, which means that when the delta is computed for the task, the `_previous_emissions` is set to the current <br> measurement, resulting in a delta of zero. |
| output_handlers | This is where one would add their custom output handlers they made. |

Also, CodeCarbon introduces the concept of **tasks** within its trackers. As of writing this, the only reference to it in the official documentation can be found in the [usage](https://mlco2.github.io/codecarbon/usage.html) section, under the "Explicit Object" subsection. If we think of the tracker traking an expriment, than tasks would be subsets of this experiment. For example, if your experiment runs from time $T_0$ to time $T_3$, than you might have loading the data as the first task from $T_0$ to $T_1$, preprocessing the data from $T_1$ to $T_2$, and training from $T_2$ to $T_3$.

Now let's take a look at some of the useful methods that trackers offer. Below is a simplified skeleton of a tracker with the relevant methods.

```python
class BaseEmissionsTracker(ABC):

  def start(self) -> None:
    pass

  def start_task(self, task_name=None) -> None:
    pass

  def stop_task(self, task_name: str = None) -> EmissionsData:
    pass

  def flush(self) -> Optional[float]:
    pass

  def stop(self) -> Optional[float]:
    pass
```

---
```python
def start(self) -> None
```
> This method is used to start the tracker. The tracker will start a scheduler that will run measurements on a different thread in the background.
---
```python
def start_task(self, task_name=None) -> None
```
> This method is used to start a task. Note that it will log a warning and be a no-op if another task is already running. Also, this method disables the background scheduler, to reduce interferences with the task. Thus, live data cannot be collected during the task, unless it is done with a different tracker.
> > `task_name`: The name of the task, which will be used in the `TaskEmissionData` object. If it is not provided, a uuid4 is generated. If it is provided, but the task name has already been used, a uuid4 is appended at the end of the name.
---
```python
def stop_task(self, task_name: str = None) -> EmissionData
```
> This method stops a task. It does not restart the background scheduler. Be cautious with this method as it seems that there are no verifications that the task actually exists when a name is provided, or that the task is still active so a task can be stopped more than once.
> > `task_name (str)`: The name of the task to stop. If it is not provided, it stops the currently running task.
> ---
> > `return (EmissionData)` The data of the task that was just stopped.
---
```python
def flush(self) -> Optional[float]
```
> This performs a measurements and flushes the current data. This means that the `out` and `task_out` methods of output handlers are called. It seems that it does not empty the internal data of the tracker, so if this method is called multiple times and the output handlers do not detect it, data points might get duplicated for tasks. Also, for some reason, the `experiment_name` of the tracker is not provided to the `task_out` method of output handler when `flush` is called.
> > `return (Optional[float])` The carbon emissions of the experiment since the tracker was started.
---
```python
def stop(self) -> Optional[float]
```
> This stops all the tasks and schedulers of the tracker. It performs a final measurement, prepares the data, and essentially flushes it like the `flush` method. However, `experiment_name` is provided to the `task_out` method in this case.
> > `return (Optional[float])` The carbon emissions of the experiment since the tracker was started.
---

### Note on using tasks

As highlighted a few times earlier, using tasks can lead to surprising behaviours. Notably, the measurement for a task is the delta between the start and the end of the task instead of measuring since the whole experiment started, and starting a task stops the background scheduler for measurements, which is not restarted when the task is completed.

In addition to this, the final call to `out` is not completely accurate. When a task is started, the internal variable `self._start_time` of the tracker is changed to the start time of the task. This leads to the value of `duration` in the `total` argument to `out` being the time between when the last task was started and the time at which `stop` or `flush` was called. However, our experiments seem to show that the measurements for energy and emissions are still accurate.

### Note on power measurements

We want to emphasize that the power measurements in the calls to `out` are the average power consumption between the last two measurements and not the average power throughout the whole experiment.

# Starting The Colab Environment <a name="sec-start-env"></a>

We will now begin the examples. First, the following step-by-step process will walk you through starting the Colab environment in case you've never done it before. If you know what you are doing, you can simply start a GPU environment and skip to the [next section](#sec-deps).

You will need an environment with a GPU. To select an environment with a GPU, you can click on `runtime` in the tool bar at the top.

A dropdown menu will appear, from which you should select `Change runtime type`

Finally, you can start the environment using the `Connect` button at the top right of the Colab page.

You can run the following cell to confirm that your environment is running and has a GPU. If everything is working as expected, it should print information about the GPU.
"""

!nvidia-smi

"""# Deps and Utils <a name="sec-deps"></a>

First, CodeCarbon needs to be installed, as it is not part of the default Colab environment. Once the installation process will be done, it should prompt you to restart the session. You need to accept the restart to be able to use CodeCarbon.
"""

!pip install codecarbon

"""Below is an alphabetical list of the imports for the tutorial."""

import csv
import datetime
import gc
import ipywidgets
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import traceback

from IPython.display import display
from IPython.display import HTML
from codecarbon import track_emissions, EmissionsTracker, OfflineEmissionsTracker
from codecarbon.core.util import backup
from codecarbon.external.logger import logger
from codecarbon.output_methods.base_output import BaseOutput
from codecarbon.output_methods.emissions_data import EmissionsData, TaskEmissionsData
from google.colab import output
from google.colab._frontend import create_scratch_cell
from threading import Lock
from torchvision.models import resnet18, ResNet18_Weights
from typing import List

"""This is not part of the tutorial, but the code in the cells is needed."""

def stop_cc_trackers():
  for obj in gc.get_objects():
    if isinstance(obj, OfflineEmissionsTracker):
      if hasattr(obj, 'final_emissions_data') and obj.final_emissions_data is None:
        print(type(obj))
        obj.stop()
  gc.collect()

"""# Colab Scratch Cells

Throughout the tutorial, you might find it useful to try a few things for yourself. For example, you might want to print some values that were computed to learn more about the formats and the like. The cell "Create Scratch Cell" will create a temporary cell on the right of the notebook where you can run code. The cell runs in the same environment as the notebook, so it has access to all the variables, classes, etc. Just be careful, these cells are not saved. If you want to save some code, make sure to do so in an appropriate format.
"""

# @title Create Scratch Cell
create_scratch_cell("# @title Exploration")

"""The Scratch Cell Generator is a scratch cell that allows you to create more scratch cells. This way, you can keep it on the side and use it to create new scratch cells without having to scroll back up to this section."""

# @title Scratch Cells Generator
create_scratch_cell("""# @title Create Scratch Cell
create_scratch_cell(\"# @title Exploration\")""")

"""# Configuration

These configuration parameters are used to set up the tutorial. Feel free to explore on your own what they do. Simply run the cell once, and a form will appear with the default configuration. You can update any value without running the cell again.

| Parameter | Type | Description |
| :--- | :---: | :--- |
| device | torch.device | This is a dropdown menu that allows you to switch between CPU and GPU <br> execution for the training of the models. If your runtime does not have a <br> GPU, than only the CPU option will be visible. A Pytorch device object is <br> automatically created under the hood. |
| nb_epochs | int | Number of epochs the model is trained for. |
| batch_size | int | Number of images per iteration during training. |
| codecarbon_experiment_name | string | CodeCarbon allows naming experiments. This value is used internally by <br> CodeCarbon, but it is also used to name some output files of the <br> experiments presented in this tutorial. |
| simple_data_file | string | Name of the file where the data of the [simple example](#subsec-simple-ex) from the [energy <br> measurement](#sec-energy-measurements) section will be stored. The data is stored using the CSV <br> format, so it is recommended to keep the CSV extension. |
| energy_data_file | string | Name of the file where the data of the [epoch based example](#subsec-epoch-based) from the <br> [energy measurement](#sec-energy-measurements) section will be stored. The data is stored using the <br> CSV format, so it is recommended to keep the CSV extension. This file <br> would contain a single CSV entry with the energy consumption of the <br> whole experiment (i.e. from the call to `tracker.start()` to the call <br> to `tracker.stop()`. |
| epoch_energy_data_file | string | Name of the file that will contain the data for each epoch of the [epoch <br> based example](#subsec-epoch-based) from the [energy measurement](#sec-energy-measurements) section. The filename is <br> automatically generated based on the values of `energy_data_file` <br> and `codecarbon_experiment_name`. Its content will also be in CSV <br> format, using the same headers as `energy_data_file`, <br> `simple_data_file`, and `power_data_file`, but with an added <br> header for the name of each task. This file will contain one entry per <br> epoch with the energy consumption and other measurements of the <br> epoch.
| live_power_data_file | string | Name of the file where the live data of the [power measurements](#sec-power-measurements) example <br> will be stored. The data is stored using the CSV format, so it is <br> recommended to keep the CSV extension. |
| power_data_file | string | Name of the file where the per-epoch data of the [power measurements](#sec-power_measurements) <br> example will be stored. The content of this file is ignored as it does not <br> contain any meaningful data for the example. It is automatically created <br> regardless, and serves as the basename for `epoch_power_data_file`. |
| epoch_power_data_file | string | This filename is automatically generated based on the values of <br> `power_data_file` and `codecarbon_experiment_name`. This <br> file will contain the data for each epoch of the experiment in the [power <br> measurements](#sec-power-measurements) example. Its content will also be in CSV format, using the <br> same headers as `energy_data_file`, `simple_data_file`, and <br> `power_data_file`, but with an added header for the name of each task. <br> It will contain one entry per epoch with the nergy consumption and other <br> measurements of the epoch. |
"""

# @title Parameters
DEFAULT_DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
DEFAULT_NB_EPOCHS = 5
DEFAULT_BATCH_SIZE = 256
DEFAULT_CODECARBON_EXPERIMENT_NAME = "epochs"
DEFAULT_SIMPLE_DATA_FILE = "codecarbon-simple.csv"
DEFAULT_ENERGY_DATA_FILE = "codecarbon-energy.csv"
DEFAULT_LIVE_POWER_DATA_FILE = "codecarbon-live.csv"
DEFAULT_POWER_DATA_FILE = "codecarbon-tasks.csv"

LABEL_WIDTH = "200px"

STATIC_LABEL_BACKGROUND = '#F7F7F7'
STATIC_LABEL_BORDER = '#9E9E9E'
if output.eval_js('document.documentElement.matches("[theme=dark]")'):
  STATIC_LABEL_BACKGROUND = '#454545'

devices = {"CPU" : torch.device("cpu")}
if torch.cuda.is_available():
  devices["GPU"] = torch.device("cuda")
device_label = ipywidgets.Label(value="device", layout=ipywidgets.Layout(width=LABEL_WIDTH))
device = ipywidgets.Dropdown(
    options=devices,
    value=DEFAULT_DEVICE,
    description=' ',
    disabled=False
)

nb_epochs_label = ipywidgets.Label(value="nb_epochs", layout=ipywidgets.Layout(width=LABEL_WIDTH))
nb_epochs = ipywidgets.IntText(
    value=DEFAULT_NB_EPOCHS,
    placeholder='Type something',
    description='(int)',
    disabled=False
)

batch_size_label = ipywidgets.Label(value="batch_size", layout=ipywidgets.Layout(width=LABEL_WIDTH))
batch_size = ipywidgets.IntText(
    value=DEFAULT_BATCH_SIZE,
    placeholder='Type something',
    description='(int)',
    disabled=False
)

codecarbon_experiment_name_label = ipywidgets.Label(value="codecarbon_experiment_name", layout=ipywidgets.Layout(width=LABEL_WIDTH))
codecarbon_experiment_name = ipywidgets.Text(
    value=DEFAULT_CODECARBON_EXPERIMENT_NAME,
    placeholder='Type something',
    description='(string)',
    disabled=False
)

simple_data_file_label = ipywidgets.Label(value="simple_data_file", layout=ipywidgets.Layout(width=LABEL_WIDTH))
simple_data_file = ipywidgets.Text(
    value=DEFAULT_SIMPLE_DATA_FILE,
    placeholder='Type something',
    description='(string)',
    disabled=False
)

energy_data_file_label = ipywidgets.Label(value="energy_data_file", layout=ipywidgets.Layout(width=LABEL_WIDTH))
energy_data_file = ipywidgets.Text(
    value=DEFAULT_ENERGY_DATA_FILE,
    placeholder='Type something',
    description='(string)',
    disabled=False
)

epoch_energy_data_file_label = ipywidgets.Label(value="epoch_energy_data_file (auto generated)", layout=ipywidgets.Layout(width='288px'))
epoch_energy_data_file = ipywidgets.Label(
    value=os.path.splitext(DEFAULT_ENERGY_DATA_FILE)[0] + "-" + DEFAULT_CODECARBON_EXPERIMENT_NAME + os.path.splitext(DEFAULT_ENERGY_DATA_FILE)[1],
    layout=ipywidgets.Layout(width='212px', border=f'solid 1px {STATIC_LABEL_BORDER}')
)

live_power_data_file_label = ipywidgets.Label(value="live_power_data_file", layout=ipywidgets.Layout(width=LABEL_WIDTH))
live_power_data_file = ipywidgets.Text(
    value=DEFAULT_LIVE_POWER_DATA_FILE,
    placeholder='Type something',
    description='(string)',
    disabled=False
)

power_data_file_label = ipywidgets.Label(value="power_data_file", layout=ipywidgets.Layout(width=LABEL_WIDTH))
power_data_file = ipywidgets.Text(
    value=DEFAULT_POWER_DATA_FILE,
    placeholder='Type something',
    description='(string)',
    layout={'description_width': 'initial'},
    disabled=False
)

epoch_power_data_file_label = ipywidgets.Label(value="epoch_power_data_file (auto generated)", layout=ipywidgets.Layout(width='288px'))
epoch_power_data_file = ipywidgets.Label(
    value=os.path.splitext(DEFAULT_POWER_DATA_FILE)[0] + "-" + DEFAULT_CODECARBON_EXPERIMENT_NAME + os.path.splitext(DEFAULT_POWER_DATA_FILE)[1],
    layout=ipywidgets.Layout(width='212px', border=f'solid 1px {STATIC_LABEL_BORDER}')
)


def codecarbon_experiment_name_callback(change):
  name = os.path.splitext(energy_data_file.value)[0]
  extension = os.path.splitext(energy_data_file.value)[1]
  epoch_energy_data_file.value = name + "-" + codecarbon_experiment_name.value + extension
  name = os.path.splitext(power_data_file.value)[0]
  extension = os.path.splitext(power_data_file.value)[1]
  epoch_power_data_file.value = name + "-" + codecarbon_experiment_name.value + extension
codecarbon_experiment_name.observe(codecarbon_experiment_name_callback, names="value")

def energy_data_file_callback(change):
  name = os.path.splitext(energy_data_file.value)[0]
  extension = os.path.splitext(energy_data_file.value)[1]
  epoch_energy_data_file.value = name + "-" + codecarbon_experiment_name.value + extension
energy_data_file.observe(energy_data_file_callback, names="value")

def power_data_file_callback(change):
  name = os.path.splitext(power_data_file.value)[0]
  extension = os.path.splitext(power_data_file.value)[1]
  epoch_power_data_file.value = name + "-" + codecarbon_experiment_name.value + extension
power_data_file.observe(power_data_file_callback, names="value")

def reset_constants(button):
  device.value = DEFAULT_DEVICE
  nb_epochs.value = DEFAULT_NB_EPOCHS
  batch_size.value = DEFAULT_BATCH_SIZE
  codecarbon_experiment_name.value = DEFAULT_CODECARBON_EXPERIMENT_NAME
  simple_data_file.value = DEFAULT_SIMPLE_DATA_FILE
  energy_data_file.value = DEFAULT_ENERGY_DATA_FILE
  live_power_data_file.value = DEFAULT_LIVE_POWER_DATA_FILE
  power_data_file.value = DEFAULT_POWER_DATA_FILE

reset_constants_button = ipywidgets.Button(
    description='Reset to defaults',
    disabled=False,
    button_style='primary',
    tooltip='Click me',
    icon='rotate-right'
)
reset_constants_button.on_click(reset_constants)

display(HTML('''<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> '''))
display(HTML(f'<style>.static_label {{ text-align:center; background:{STATIC_LABEL_BACKGROUND} }}</style>'))
epoch_energy_data_file.add_class("static_label")
epoch_power_data_file.add_class("static_label")
display(ipywidgets.HBox([device_label, device]))
display(ipywidgets.HBox([nb_epochs_label, nb_epochs]))
display(ipywidgets.HBox([batch_size_label, batch_size]))
display(ipywidgets.HBox([codecarbon_experiment_name_label, codecarbon_experiment_name]))
display(ipywidgets.HBox([simple_data_file_label, simple_data_file]))
display(ipywidgets.HBox([energy_data_file_label, energy_data_file]))
display(ipywidgets.HBox([epoch_energy_data_file_label, epoch_energy_data_file]))
display(ipywidgets.HBox([live_power_data_file_label, live_power_data_file]))
display(ipywidgets.HBox([power_data_file_label, power_data_file]))
display(ipywidgets.HBox([epoch_power_data_file_label, epoch_power_data_file]))
display(reset_constants_button)

"""If you are using a scratch cell on the side, or want to use these parameters in the exercises at the end, you can do so by appending `.value` to the name of the variables. For example, to get the number of epochs, you would use `nb_epochs.value`.

# Custom Output Handlers <a name="sec-cc-extras"></a>

CodeCarbon allows defining custom output objects to change how the data is collected from experiments. We explain CodeCarbon output handlers in this previous [section](#01). CodeCarbon documentation on how to output the data can be found [here](https://mlco2.github.io/codecarbon/output.html).

We introduce two new output handlers that will be used in examples later in this tutorial.

The `SimpleFileOutput` class is adapted from the default file output provided by CodeCarbon [here](https://github.com/mlco2/codecarbon/blob/master/codecarbon/output_methods/file.py). The main modification is the naming scheme of the output file for tasks (in the `task_out` method), and the default name of the outputs. The simpler naming scheming is used to automate some parts of the tutorial to easily retrieve data.
"""

class SimpleFileOutput(BaseOutput):
  """
  Saves experiment artifacts to a file
  """

  def __init__(
    self, output_file_name: str = "codecarbon.csv", output_dir: str = ".", on_csv_write: str = "append"
  ):
    if on_csv_write not in {"append", "update"}:
      raise ValueError(
        f"Unknown `on_csv_write` value: {on_csv_write}"
        + " (should be one of 'append' or 'update'"
      )
    self.output_file_name: str = output_file_name
    if not os.path.exists(output_dir):
      raise OSError(f"Folder '{output_dir}' doesn't exist !")
    self.output_dir: str = output_dir
    self.on_csv_write: str = on_csv_write
    self.save_file_path = os.path.join(self.output_dir, self.output_file_name)
    logger.info(
      f"Emissions data (if any) will be saved to file {os.path.abspath(self.save_file_path)}"
    )

  def has_valid_headers(self, data: EmissionsData):
    with open(self.save_file_path) as csv_file:
      csv_reader = csv.DictReader(csv_file)
      dict_from_csv = dict(list(csv_reader)[0])
      list_of_column_names = list(dict_from_csv.keys())
      return list(data.values.keys()) == list_of_column_names

  def to_csv(self, total: EmissionsData, delta: EmissionsData):
    """
    Save the emissions data to a CSV file.
    If the file already exists, append the new data to it.
    param `delta` is not used in this method.
    """
    file_exists: bool = os.path.isfile(self.save_file_path)
    if file_exists and not self.has_valid_headers(total):
      logger.warning("The CSV format have changed, backing up old emission file.")
      backup(self.save_file_path)
      file_exists = False
    new_df = pd.DataFrame.from_records([dict(total.values)])
    if not file_exists:
      df = new_df
    elif self.on_csv_write == "append":
      df = pd.read_csv(self.save_file_path)
      df = pd.concat([df, new_df])
    else:
      df = pd.read_csv(self.save_file_path)
      df_run = df.loc[df.run_id == total.run_id]
      if len(df_run) < 1:
        df = pd.concat([df, new_df])
      elif len(df_run) > 1:
        logger.warning(
          f"CSV contains more than 1 ({len(df_run)})"
          + f" rows with current run ID ({total.run_id})."
          + "Appending instead of updating."
        )
        df = pd.concat([df, new_df])
      else:
        df.at[df.run_id == total.run_id, total.values.keys()] = (
          total.values.values()
        )

    df.to_csv(self.save_file_path, index=False)

  def out(self, total: EmissionsData, delta: EmissionsData):
    self.to_csv(total, delta)

  def live_out(self, total: EmissionsData, delta: EmissionsData):
    pass

  def task_out(self, data: List[TaskEmissionsData], experiment_name: str):
    run_id = data[0].run_id
    split = os.path.splitext(self.save_file_path)
    save_task_file_path = split[0] + "-" + experiment_name + split[1]
    df = pd.DataFrame(columns=data[0].values.keys())
    new_df = pd.DataFrame.from_records(
        [dict(data_point.values) for data_point in data]
    )
    # Filter out empty or all-NA columns, to avoid warnings from Pandas
    new_df = new_df.dropna(axis=1, how="all")
    df = pd.concat([df, new_df], ignore_index=True)
    df.to_csv(save_task_file_path, index=False)

"""The `SafeLiveFileOutput` class is an output handler optimized for speed. To achieve this with simplicity, it only supports live output. CodeCarbon trackers have a configuration named `measure_power_secs`, which sets how often a tracker takes measurements. This value can go below 1 second, but reusing the techniques used by the file output provided by CodeCarbon or the `SimpleFileOutput` class allows race conditions.

The internals for CodeCarbon use a scheduler that will start measurements on a thread every `measure_power_secs` (see the scheduler [here](https://github.com/mlco2/codecarbon/blob/master/codecarbon/external/scheduler.py)). However, this scheduler schedules the next task before executing the measurement (which makes sense to keep the intervals as regular as possible). Unfortunately, a side effect of this is that when the intervals are short, it is possible to have two measurements running at the same time.

The `SafeLiveFileOutput` adds concurrency control to ensure two measurements do not output at the time by using a simple lock. It also caches all the live data in memory to make the live output faster. The cached data is flushed to disk when a tracker is stopped or `flush` is called.
"""

class SafeLiveFileOutput(BaseOutput):
  """
  Saves experiment artifacts to a file
  """

  def __init__(
    self, output_file_name: str = "codecarbon-live.csv", output_dir: str = "."
  ):
    self.output_file_name: str = output_file_name
    if not os.path.exists(output_dir):
      raise OSError(f"Folder '{output_dir}' doesn't exist !")
    self.output_dir: str = output_dir
    self.save_file_path = os.path.join(self.output_dir, self.output_file_name)
    logger.info(
      f"Emissions data (if any) will be saved to file {os.path.abspath(self.save_file_path)}"
    )
    self.lock = Lock()
    self.data = []

  def add_data(self, total: EmissionsData, delta: EmissionsData):
    self.data.append(total)

  def out(self, total: EmissionsData, delta: EmissionsData):
    locked = False
    try:
      locked = self.lock.acquire()
      df = pd.DataFrame.from_records(
        [dict(data_point.values) for data_point in self.data]
      )
      df.to_csv(self.save_file_path, index=False)
      self.data = []
    except Exception as error:
      error_msg = traceback.format_exc()
      print(error_msg)
      print(f"Unexpected {error=}, {type(error)=}")
    finally:
      if locked:
        self.lock.release()

  def live_out(self, total: EmissionsData, delta: EmissionsData):
    locked = False
    try:
      locked = self.lock.acquire()
      self.add_data(total, delta)
    except Exception as error:
      error_msg = traceback.format_exc()
      print(error_msg)
      print(f"Unexpected {error=}, {type(error)=}")
    finally:
      if locked:
        self.lock.release()

  def task_out(self, data: List[TaskEmissionsData], experiment_name: str):
    pass

"""# Model <a name="sec-model"></a>

The `CNN` class is a simple convolutional neural network designed to be trained on the CIFAR10 dataset, which will be used in this tutorial.
"""

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 24, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(24, 48, 5)
        self.fc1 = nn.Linear(1728, 256)
        self.fc2 = nn.Linear(256, 256)
        self.fc3 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return F.softmax(x, dim=1)

"""Below is the train loop use to train the CNN model. The `cc_tracker` argument is a CodeCarbon tracker used to get measurements for each epoch of the training."""

def train(model : CNN,
          nb_epochs : int,
          loader : torch.utils.data.DataLoader,
          optimizer : torch.optim.Optimizer,
          loss : nn.CrossEntropyLoss,
          device : torch.device,
          cc_tracker : OfflineEmissionsTracker
  ):
  model.train()
  losses = []
  for epoch in range(nb_epochs):  # loop over the dataset multiple times

      running_loss = 0.0
      if cc_tracker is not None:
        cc_tracker.start_task(task_name=f'epoch-{epoch}')
      for i, data in enumerate(loader, 0):
          # get the inputs where data is a list of [inputs, labels]
          inputs, labels = data
          inputs, labels = inputs.to(device), labels.to(device)

          # zero the parameter gradients
          optimizer.zero_grad()

          # forward + backward + optimize
          outputs = model(inputs)
          l = loss(outputs, labels)
          l.backward()
          optimizer.step()

          # update statistics
          running_loss += l.item()

      if cc_tracker is not None:
        cc_tracker.stop_task(task_name=f'epoch-{epoch}')
      losses.append(running_loss / len(loader))
      running_loss = 0.0

"""# Data

This simply loads the CIFAR10 dataset and prepares a data loader for the training. For more information about the dataset, please see the [website](https://www.cs.toronto.edu/~kriz/cifar.html) and the [paper](https://www.cs.toronto.edu/~kriz/learning-features-2009-TR.pdf) that introduced it.
"""

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])


trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size.value,
                                          shuffle=True, num_workers=2)

images, _ = next(iter(trainloader))
images.shape

"""# Energy Measurements <a name="sec-energy-measurements"></a>

We introduce two examples that present different energy measurements that can be done using CodeCarbon trackers.

## Simple Example <a name="subsec-simple-ex"></a>

This first example introduces a simple usage of CodeCarbon to obtain the energy consumption of a task.

First, we create a simple CNN that we will train on CIFAR10. We train using a simple Stochastic Gradient Descent approach.
"""

simple_net = CNN()
simple_net.to(device=device.value)
simple_criterion = nn.CrossEntropyLoss()
simple_sgd_opt = torch.optim.SGD(simple_net.parameters(), lr=0.05, momentum=0.9)

"""Now we create a CodeCarbon tracker. Most of these configuration parameters are placeholders for required data that is not relevant to the example. For information on those parameters, please refer to the official CodeCarbon documentation. The important ones are `save_to_file=False`, which disables the default file output mechanism. Next is the `output_handlers` parameter, where we create an output handler of type `SimpleFileOutput`, which was introduced in the [CodeCarbon Output Handlers](#sec-cc-extras) section of the tutorial. Finally, `experiment_name` is set to follow a predetermined naming scheme of the output files so the later step can easily load them."""

simple_tracker = OfflineEmissionsTracker(
    project_name="CIFAR",
    country_iso_code="USA",
    region="California",
    save_to_file=False,
    output_handlers=[SimpleFileOutput(output_file_name=simple_data_file.value)],
    experiment_name=codecarbon_experiment_name.value,
    log_level="warning",
)

"""To run the experiment, it suffices to start the tracker right before performing the task to track, and stopping it right after."""

simple_tracker.start()
train(
  model=simple_net,
  nb_epochs=nb_epochs.value,
  loader=trainloader,
  optimizer=simple_sgd_opt,
  loss=simple_criterion,
  device=device.value,
  cc_tracker=None,
)
simple_tracker.stop()

print('Finished Training')

"""We can now load the CSV data from the file into a Pandas dataframe. Notice how the file name is exactly the one configured for the output handler earlier. We print the list of column to get an idea of what they are, but do not rely on all the data types. You should refer to the official documentation for this."""

simple_data = pd.read_csv(simple_data_file.value, parse_dates=[0])
simple_data.info(verbose=True, memory_usage=False, show_counts=True)

"""Finally, we can observe a subset of the data below. We can see the different energy measurements for the CPU, the GPU and the RAM along with the total consumption."""

simple_data[["timestamp", "project_name", "duration", "cpu_energy", "gpu_energy", "ram_energy", "energy_consumed"]]

"""This is the end of this first experiment. If you would like to run it again, you can run the cell below once to generate a reset button. This button will reset the state of the notebook to allow running the experiment again."""

# Commented out IPython magic to ensure Python compatibility.
# @title Reset example
output_reset_energy_simple = ipywidgets.Output()
def reset_energy_simple(button):
  with output_reset_energy_simple:
    stop_cc_trackers()
#     %rm $simple_data_file.value
    if "simple_net" in locals():
      simple_net.to(torch.device('cpu'))
#     %xdel simple_net
#     %xdel simple_criterion
#     %xdel simple_sgd_opt
#     %xdel simple_tracker
#     %xdel simple_data
    gc.collect()
    output_reset_energy_simple.clear_output(wait=True)
    print("Ready to go")

button_reset_energy_simple = ipywidgets.Button(
    description='Reset example',
    disabled=False,
    button_style='primary',
    tooltip='Click me',
    icon='rotate-right'
)
button_reset_energy_simple.on_click(reset_energy_simple)
display(HTML('''<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> '''))
display(ipywidgets.HBox([button_reset_energy_simple, output_reset_energy_simple]))

"""## Epochs Based Example <a name="subsec-epoch-based"></a>

This example will introduce a way to get more fine-grained data from an experiment. We will use CodeCarbon tasks to track energy per epoch of training.

Once again, we create a simple CNN that we will train on CIFAR10 using the same technique as in the previous example.
"""

energy_net = CNN()
energy_net.to(device=device.value)
energy_criterion = nn.CrossEntropyLoss()
energy_sgd_opt = torch.optim.SGD(energy_net.parameters(), lr=0.05, momentum=0.9)

"""A tracker is created once again. Notice the addition of the `api_call_interval` in the configuration. As stated in the [CodeCarbon Overview](#sec-cc-overview), this is required when using tasks in order to avoid losing data of some or all tasks."""

energy_tracker = OfflineEmissionsTracker(
    project_name="CIFAR",
    country_iso_code="USA",
    region="California",
    save_to_file=False,
    output_handlers=[SimpleFileOutput(output_file_name=energy_data_file.value)],
    api_call_interval=-1, # Required, otherwise the energy consumed by the tasks will be zero.
    experiment_name=codecarbon_experiment_name.value,
    log_level="warning",
)

"""Finally, we proceed as in the previous example. Remember from the [Model](#sec-model) that the train function can take a CodeCarbon tracker. When given a tracker, it starts a task for each epoch and stops it when the epoch is done."""

energy_tracker.start()
train(
  model=energy_net,
  nb_epochs=nb_epochs.value,
  loader=trainloader,
  optimizer=energy_sgd_opt,
  loss=energy_criterion,
  device=device.value,
  cc_tracker=energy_tracker,
)
energy_tracker.stop()

print('Finished Training')

"""Finally, we load the task data generated during the experiment. After a few transformations, we extract the duration, and the energy consumption of each epochs, to which we add a summary column named `experiment`, which contains the results for the whole experiment, aggregated from the epochs."""

energy_epochs_data = pd.read_csv(epoch_energy_data_file.value, parse_dates=[1])
energy_exp_results = energy_epochs_data.pivot(columns=["task_name"], values=["duration", "cpu_energy", "ram_energy", "gpu_energy", "energy_consumed"], index=["project_name"]).transpose().unstack().droplevel(["project_name"], axis=1)
energy_exp_results.columns = energy_exp_results.columns.set_names("measurement")
energy_exp_results.insert(len(energy_exp_results.columns), "experiment", energy_exp_results.sum(axis=1))
energy_exp_results

"""This is the end of this example. As before, there is a cell below you can run once to generate a reset button to restart this example as many as you want."""

# Commented out IPython magic to ensure Python compatibility.
# @title Reset example
output_reset_energy_epochs = ipywidgets.Output()
def reset_energy_epochs(button):
  with output_reset_energy_epochs:
    stop_cc_trackers()
#     %rm $energy_data_file.value
#     %rm $energy_task_data_file.value
    if "energy_net" in locals():
      energy_net.to(torch.device('cpu'))
#     %xdel energy_net
#     %xdel energy_criterion
#     %xdel energy_sgd_opt
#     %xdel energy_tracker
#     %xdel energy_epochs_data
#     %xdel energy_exp_data
    gc.collect()
    output_reset_energy_epochs.clear_output(wait=True)
    print("Ready to go")

button_reset_energy_epochs = ipywidgets.Button(
    description='Reset example',
    disabled=False,
    button_style='primary',
    tooltip='Click me',
    icon='rotate-right'
)
button_reset_energy_epochs.on_click(reset_energy_epochs)
display(HTML('''<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> '''))
display(ipywidgets.HBox([button_reset_energy_epochs, output_reset_energy_epochs]))

"""# Power Measurements <a name="sec-power-measurements"></a>

This experiment of the tutorial introduces how CodeCarbon can be used to observe the power fluctuations. While CodeCarbon is not specifically designed for power measurements in this way, it is a nice to have, especially for visualization purposes or exploration of machine learning behaviours.

## Set Up

The code below simply creates an untrained instance of the model which is placed on the configured device (GPU or CPU). It creates the loss function used during training and the optimizer for the experiments (a simple Stochastic Gradient Descent approach)
"""

net = CNN()
net.to(device=device.value)
criterion = nn.CrossEntropyLoss()
sgd_opt = torch.optim.SGD(net.parameters(), lr=0.05, momentum=0.9)

"""This is the configuration of the tracker used to gather live data of the experiments. Notice that `measure_power_secs` is set to take measurements every 100ms. The parameter `save_to_file=False` essentially disables the default CodeCarbon file output (which is not needed for the experiments). The parameter `output_handlers` is where the custom output class introduced by the [CodeCarbon Extras](#sec-cc-extras) section is used. The `api_call_interval` parameter indicates after how many measurements the `live_out` method of the output handlers should be called. Finally, the parameter `allow_multiple_runs=True` is required to have this multi-tracker set up."""

live_tracker = OfflineEmissionsTracker(
    project_name="CIFAR",
    measure_power_secs=0.1,
    country_iso_code="USA",
    region="California",
    save_to_file=False,
    output_handlers=[SafeLiveFileOutput(output_file_name=live_power_data_file.value)],
    api_call_interval=1,
    allow_multiple_runs=True,
    log_level="warning",
)

"""Below is the configuration for the tracker that will monitor epochs of the training experiment. It needs to be a separate tracker from the one gathering live data, because starting a task with the method `start_task` of a CodeCarbon tracker disables the scheduler for measurement, which is essential to get live data."""

task_tracker = OfflineEmissionsTracker(
    project_name="CIFAR",
    country_iso_code="USA",
    region="California",
    save_to_file=False,
    output_handlers=[SimpleFileOutput(output_file_name=power_data_file.value)],
    api_call_interval=1,
    experiment_name=codecarbon_experiment_name.value,
    allow_multiple_runs=True,
    log_level="warning",
)

"""## Training

Here we get the training going and along with measurements! You might see warnings about the scheduler not running for a long period (especially if running on the CPU instead of GPU). These can be ignored as the results that would be affected are not used later on.
"""

task_tracker.start()
live_tracker.start()
train(
  model=net,
  nb_epochs=nb_epochs.value,
  loader=trainloader,
  optimizer=sgd_opt,
  loss=criterion,
  device=device.value,
  cc_tracker=task_tracker,
)
live_tracker.stop()
task_tracker.stop()

print('Finished Training')

"""## Visualization

Here, we load both the live output from the experiments, and the data from each epochs.
"""

power_data = pd.read_csv(live_power_data_file.value, parse_dates=[0])
epochs_tasks = pd.read_csv(epoch_power_data_file.value, parse_dates=[1])

"""Each data points of the live output is matched to its corresponding epoch."""

prev = None
epochs_data = {}
for _, epoch in epochs_tasks.iterrows():
  if prev is None:
    epochs_data[epoch.task_name] = power_data[power_data['timestamp'] <= epoch.timestamp]
  else:
    tmp = power_data[power_data['timestamp'] <= epoch.timestamp]
    epochs_data[epoch.task_name] = tmp[tmp['timestamp'] > prev.timestamp]
  prev = epoch

"""This is just a nice to have to dynamically set the plot size based on the number of epochs, and it chooses the colormap for visualization purposes."""

COLORMAP = mpl.colormaps['viridis']
X_SIZE = nb_epochs.value * 2.5 # In inches
Y_SIZE = 6 # In inches

"""Finally, we plot the power consumption for each epoch of training!"""

plt.figure(figsize=(X_SIZE,Y_SIZE))
colors = iter(COLORMAP(np.linspace(0, 1, nb_epochs.value)))
for epoch_name, epoch_data in epochs_data.items():
  color = next(colors)
  plt.plot(epoch_data['duration'], epoch_data['gpu_power'], marker= ',', alpha=.998, label =(f'{epoch_name}-GPU'), c=color)
  # plt.plot(epoch_data['duration'], epoch_data['cpu_power'], marker= '.', alpha=.998, label =(f'{epoch_name}-CPU'), c=color)
plt.xlabel('time (s)')
plt.ylabel('power (W)')
plt.legend(bbox_to_anchor=(1,1))
plt.show()

"""## Reset

This is the end of this last example. A reset button is provided if you run the cell below once. This way, you can also restart this experient.
"""

# Commented out IPython magic to ensure Python compatibility.
# @title Reset example
output_reset_power_measurements = ipywidgets.Output()
def reset_power_measurements(button):
  with output_reset_power_measurements:
    stop_cc_trackers()
#     %rm $live_data_file.value
#     %rm $task_data_file.value
#     %rm $exp_task_data_file.value
    if "net" in locals():
      net.to(torch.device('cpu'))
#     %xdel net
#     %xdel criterion
#     %xdel sgd_opt
#     %xdel live_tracker
#     %xdel task_tracker
#     %xdel power_data
#     %xdel epochs_tasks
#     %xdel prev
#     %xdel epochs_data
#     %xdel COLORMAP
#     %xdel X_SIZE
#     %xdel Y_SIZE
#     %xdel colors
    gc.collect()
    output_reset_power_measurements.clear_output(wait=True)
    print("Ready to go")

button_reset_power_measurements = ipywidgets.Button(
    description='Reset example',
    disabled=False,
    button_style='primary',
    tooltip='Click me',
    icon='rotate-right'
)
button_reset_power_measurements.on_click(reset_power_measurements)
display(HTML('''<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> '''))
display(ipywidgets.HBox([button_reset_power_measurements, output_reset_power_measurements]))

"""# Exercises

Let's explore with a different model. Below you will find a code cell containing starting code to run ResNet18. The starting code allows fine-tuning of ResNet18 on the CIFAR10 dataset.

This is mostly an open-ended exercise to explore what to do with CodeCarbon.

As a first step, try to modify the provided code to measure the energy consumption per epochs. Once you have this going, maybe explore finer grained data, and see if the energy consumption is uniform throughout an epoch.

You could also explore the effect of various parameters such as the size of batches. Does power scale linearly with respect to the batch size? Does a given batch size seem optimal energy wise?
"""

# @title ResNet18 Starter Code
weights = ResNet18_Weights.IMAGENET1K_V1
resnet = resnet18(weights=weights)
# Freeze the whole model
for param in resnet.parameters():
  param.requires_grad = False
# Replace the head for CIFAR10
resnet.fc = nn.Sequential(
  nn.Linear(512, 256),
  nn.ReLU(),
  nn.Linear(256, 10),
  nn.Softmax(dim=1)
)

resnet_optim = torch.optim.SGD(resnet.parameters(), lr=0.05, momentum=0.9)
resnet_loss = nn.CrossEntropyLoss()

def training_loop(n_epochs, optimizer, model, loss_fn, loader, device):
  model.train()
  losses = []

  for epoch in range(1, n_epochs + 1):

    running_loss = 0.0
    for imgs, labels in loader:
      # move the data to the device
      imgs = imgs.to(device)
      labels = labels.to(device)

      # zero the parameter gradients
      optimizer.zero_grad()

      # forward + backward + optimize
      outputs = model(imgs)
      loss = loss_fn(outputs, labels)
      loss.backward()
      optimizer.step()

      # update statistics
      running_loss += loss.item()

    losses.append(running_loss / len(loader))
    print(f'{datetime.datetime.now()}, Epoch: {epoch}, Training loss: {running_loss / len(loader)}')
  return losses

resnet.to(device=device.value)
losses = training_loop(
  n_epochs=1,
  optimizer=resnet_optim,
  model=resnet,
  loss_fn=resnet_loss,
  loader=trainloader,
  device=device.value
)

"""# Conclusion

Thank you for going through this tutorial, we hope you found it useful. We want to once again provide a link to the official CodeCarbon [documentation](https://mlco2.github.io/codecarbon/), a link to the official [website](https://codecarbon.io/) of the library and a link to the [source code](https://github.com/mlco2/codecarbon).
"""